# Generated by Django 3.1 on 2020-09-10 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('author', models.CharField(default='Luna Lovegood Limerick', max_length=100)),
                ('main', models.TextField()),
                ('teaserSummary', models.CharField(max_length=250)),
                ('featured', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=True)),
                ('articleOfTheWeek', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
